### PR TITLE
fix bug in Insight.address()

### LINKED ISSUE #1175: Insight.address() doesn't work
See https://github.com/bitpay/bitcore-explorers/commit/05dd58a4c5bf5a069dcc64f76665fee855fe9699

The string response body from the XHR is passed to AddressInfo.fromInsight() which expects an object and not a string.

Maybe if AddressInfo had proper type annotations, the compiler would have warned about this?

### PR DESCRIPTION
**Pull request by maraoz**
fixes https://github.com/bitpay/bitcore/issues/1175

### CODE REVIEW

File: test/models/addressinfo.js [hunk 1]
```diff
@@ -12,10 +9,11 @@ describe('AddressInfo', function() {
 
   describe('instantiation', function() {
 
-    var data = require('./sampleAddressFromInsight.json');
+    var data = JSON.stringify(require('./sampleAddressFromInsight.json'));
```
Comment (dskloet) [inline test/models/addressinfo.js]: It should still work with the JS object as well. Not just with the string. Do you want to test both?

File: test/insight.js [hunk 2]
```diff
@@ -141,7 +141,7 @@ describe('Insight', function() {
     var data = require('./models/sampleAddressFromInsight.json');
```
Comment (dskloet) [inline test/insight.js:161]: How about making sampleAddressFromInsight itself stringified instead of stringifying it in both places where it's used?

**Comment by maraoz** [comment]
I added this test to be sure it works for strings and objects: https://github.com/bitpay/bitcore-explorers/pull/18/files#diff-9a1575ea9a5c3ae37016c0af0f68ac73R16

**Comment by dskloet** [comment]
LGTM (is there a button for that somewhere?)

File: lib/models/addressinfo.js [hunk 3]
```diff
@@ -27,6 +27,9 @@ function AddressInfo(param) {
 }
 
 AddressInfo.fromInsight = function(param) {
+  if (_.isString(param)) {
```
Comment (braydonf) [inline lib/models/addressinfo.js:30]: Instead of JSON parsing here where an error in parsing would cause a crash, should we try/catch at: https://github.com/bitpay/bitcore-explorers/blob/master/lib/insight.js#L122 and then pass an error in the callback?
